import './globals.css'
import type {Metadata} from 'next'
import {Libre_Franklin, Roboto_Mono} from 'next/font/google'

const inter = Libre_Franklin({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${inter.variable}`}>
        <body className="p-4">{children}</body>
        </html>
    )
}
